name: Binary

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: "Binary (via nuitka)"
      run: |
        pip install nuitka
        make bin

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: jpeg2000-reader
        path: jpeg2000-reader

